apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: payments
resources:
  - node-pools.yaml
  - kafka.yaml
  - users.yaml
  - disruption-budgets.yaml
  - network-policy.yaml
commonLabels:
  app.kubernetes.io/part-of: payment-platform

