apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cockroachdb
  namespace: payments
spec:
  minAvailable: 2
  unhealthyPodEvictionPolicy: IfHealthyBudget
  selector:
    matchLabels:
      app.kubernetes.io/name: cockroachdb

