apiVersion: v1
kind: ServiceAccount
metadata:
  name: cockroach-cert-issuer
  namespace: payments
  annotations:
    payment.example/workload-identity: cert-manager-cockroach-node
automountServiceAccountToken: false
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cockroach-node-vault-pki
  namespace: payments
spec:
  vault:
    server: https://vault-active.vault.svc.cluster.local:8200
    path: pki_cockroach/sign/node
    caBundleSecretRef:
      name: vault-public-ca
      key: ca.crt
    auth:
      kubernetes:
        mountPath: /v1/auth/kubernetes
        role: cert-manager-cockroach-node
        serviceAccountRef:
          name: cockroach-cert-issuer

