apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: payments
resources:
  - site-config.yaml
  - priority-class.yaml
  - issuer.yaml
  - service.yaml
  - statefulset.yaml
  - disruption-budget.yaml
  - network-policy.yaml
commonLabels:
  app.kubernetes.io/part-of: payment-platform

