apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - sidecar-config.yaml
  - gateway-certificates.yaml
  - gateway.yaml
  - network-policy.yaml
  - monitoring.yaml
commonLabels:
  app.kubernetes.io/part-of: payment-platform

