// Package escrow implements bounded, region-local spending authority.  Money
// remains in the ledger; this package moves only the right to authorize a
// future debit.
package escrow

import (
	"context"
	"errors"

	"github.com/example/payment-platform/internal/ledger"
	"github.com/jackc/pgx/v5"
)

var (
	ErrInvalidArgument           = errors.New("escrow: invalid argument")
	ErrInsufficientRights        = errors.New("escrow: insufficient regional rights")
	ErrCertificateInvalid        = errors.New("escrow: invalid transfer certificate")
	ErrCertificateConflict       = errors.New("escrow: transfer id reused with different certificate")
	ErrConsumptionReceiptInvalid = errors.New("escrow: invalid destination consumption receipt")
	ErrAuthorityConflict         = errors.New("escrow: authority already exists with different total")
	ErrEffectConflict            = errors.New("escrow: effect id reused with a different request")
	ErrConsumptionProofMissing   = errors.New("escrow: durable destination consumption proof missing")
)

type EffectKind string

const (
	EffectAllocate EffectKind = "ALLOCATE"
	EffectSpend    EffectKind = "SPEND"
	EffectReturn   EffectKind = "RETURN"
)

func (kind EffectKind) valid() bool {
	return kind == EffectAllocate || kind == EffectSpend || kind == EffectReturn
}

// EffectRequest is the complete identity of one authority mutation. EffectID
// is generated by the durable issuer/counter service, never from a wall clock,
// and is stable across process, connection and region retries.
type EffectRequest struct {
	EffectID  string
	AccountID string
	AssetID   string
	Region    string
	Amount    ledger.Amount
}

func (request EffectRequest) validate() error {
	if request.EffectID == "" || len(request.EffectID) > 512 || request.AccountID == "" ||
		request.AssetID == "" || request.Region == "" || request.Amount.Sign() <= 0 {
		return ErrInvalidArgument
	}
	return nil
}

type EffectReceipt struct {
	EffectID    string
	Kind        EffectKind
	RequestHash [32]byte
	Duplicate   bool
}

// DB is deliberately the small pgx boundary needed by the protocol.  A
// pgxpool.Pool satisfies it; in production that pool points at the consensus
// SQL authority for the account shard.
type DB interface {
	BeginTx(context.Context, pgx.TxOptions) (pgx.Tx, error)
}

type Authority struct {
	AccountID      string
	AssetID        string
	Total          ledger.Amount
	Unallocated    ledger.Amount
	Version        int64
	RegionalRights map[string]ledger.Amount
	InTransit      ledger.Amount
	OfflineIssued  ledger.Amount
	FoldedOffline  ledger.Amount
}

func (a Authority) Conserved() bool {
	if a.Total.Sign() < 0 || a.Unallocated.Sign() < 0 || a.InTransit.Sign() < 0 ||
		a.OfflineIssued.Sign() < 0 || a.FoldedOffline.Sign() < 0 ||
		a.OfflineIssued.Cmp(a.FoldedOffline) != 0 {
		return false
	}
	total, err := a.Unallocated.Add(a.InTransit)
	if err != nil {
		return false
	}
	total, err = total.Add(a.OfflineIssued)
	if err != nil {
		return false
	}
	for _, amount := range a.RegionalRights {
		if amount.Sign() < 0 {
			return false
		}
		total, err = total.Add(amount)
		if err != nil {
			return false
		}
	}
	return total.Cmp(a.Total) == 0
}

type TransferRequest struct {
	TransferID               string
	AccountID                string
	AssetID                  string
	SourceRegion             string
	DestinationRegion        string
	SourceLegalEntityID      string
	DestinationLegalEntityID string
	Amount                   ledger.Amount
}

type Consumption struct {
	TransferID string
	Duplicate  bool
	Receipt    ConsumptionReceipt
}
